import { useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { CheckCircle2, Edit3, MoreHorizontal, ShieldCheck, Trash2 } from "lucide-react";
import { listings } from "@/lib/campus-data";
import { ListingImage } from "@/components/listing-card";
import { Button } from "@/components/ui/button";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
export const Route = createFileRoute("/my-listings")({ head: () => ({ meta: [{ title: "My Listings — Campus Crate" }, { name: "description", content: "Manage your active Campus Crate community posts." }, { property: "og:title", content: "My Listings — Campus Crate" }, { property: "og:description", content: "Manage your active Campus Crate community posts." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: MyListings });
function MyListings() {
  const [tab, setTab] = useState("all"); const [done, setDone] = useState([]); const [removed, setRemoved] = useState([]);
  const mine = listings.filter((item) => [3,5,7,8].includes(item.id) && !removed.includes(item.id) && (tab === "all" || item.module === tab));
  const action = { lost: "Mark resolved", market: "Mark sold", housing: "Mark rented" };
  return <main className="container-shell py-10"><section className="flex flex-col justify-between gap-5 border-b border-border pb-8 sm:flex-row sm:items-center"><div className="flex items-center gap-4"><div className="flex size-16 items-center justify-center rounded-full bg-primary text-xl font-bold text-primary-foreground">NB</div><div><div className="flex flex-wrap items-center gap-2"><h1 className="font-display text-2xl font-bold">Nafiz Barakah</h1><span className="flex items-center gap-1 rounded-full bg-success-soft px-2 py-1 text-xs font-semibold text-success"><ShieldCheck className="size-3.5"/>Verified Student</span></div><p className="mt-1 text-sm text-muted-foreground">Member since January 2026 · University community</p></div></div><Button asChild><Link to="/edit-profile"><Edit3/>Edit profile</Link></Button></section>
    <section className="py-8"><div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="font-display text-xl font-semibold">My listings</h2><p className="text-sm text-muted-foreground">Manage everything you've shared with campus.</p></div><Tabs value={tab} onValueChange={setTab}><TabsList><TabsTrigger value="all">All</TabsTrigger><TabsTrigger value="lost">Lost & Found</TabsTrigger><TabsTrigger value="market">Marketplace</TabsTrigger><TabsTrigger value="housing">To-Let</TabsTrigger></TabsList></Tabs></div>
      <div className="overflow-hidden rounded-xl border border-border bg-card">{mine.map((item) => <article key={item.id} className="grid gap-4 border-b border-border p-4 last:border-0 sm:grid-cols-[88px_1fr_auto] sm:items-center"><div className="h-20 overflow-hidden rounded-lg"><ListingImage listing={item}/></div><div><div className="mb-1 flex items-center gap-2"><h3 className="font-semibold">{item.title}</h3><span className="rounded-full bg-accent px-2 py-0.5 text-[10px] font-bold uppercase text-accent-foreground">{item.tag}</span></div><p className="text-sm text-muted-foreground">{item.detail} · {item.meta}</p>{done.includes(item.id) && <p className="mt-1 flex items-center gap-1 text-xs font-semibold text-success"><CheckCircle2 className="size-3.5"/>Completed</p>}</div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={done.includes(item.id)} onClick={() => setDone([...done,item.id])}><CheckCircle2/>{action[item.module]}</Button><Button size="icon" variant="ghost" aria-label="Edit listing"><Edit3/></Button><Button size="icon" variant="ghost" aria-label="Delete listing" onClick={() => setRemoved([...removed,item.id])}><Trash2/></Button><Button size="icon" variant="ghost" aria-label="More options"><MoreHorizontal/></Button></div></article>)}{mine.length === 0 && <p className="py-16 text-center text-muted-foreground">No listings in this category.</p>}</div>
    </section>
  </main>;
}
