/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditProfileRouteImport } from './routes/edit-profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LostAndFoundRouteImport } from './routes/lost-and-found'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MyListingsRouteImport } from './routes/my-listings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ToLetRouteImport } from './routes/to-let'
import { Route as ListingIdRouteImport } from './routes/listing.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditProfileRoute = EditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LostAndFoundRoute = LostAndFoundRouteImport.update({
  id: '/lost-and-found',
  path: '/lost-and-found',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListingsRoute = MyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ToLetRoute = ToLetRouteImport.update({
  id: '/to-let',
  path: '/to-let',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/edit-profile': typeof EditProfileRoute
  '/login': typeof LoginRoute
  '/lost-and-found': typeof LostAndFoundRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-listings': typeof MyListingsRoute
  '/signup': typeof SignupRoute
  '/to-let': typeof ToLetRoute
  '/listing/$id': typeof ListingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/edit-profile': typeof EditProfileRoute
  '/login': typeof LoginRoute
  '/lost-and-found': typeof LostAndFoundRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-listings': typeof MyListingsRoute
  '/signup': typeof SignupRoute
  '/to-let': typeof ToLetRoute
  '/listing/$id': typeof ListingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/edit-profile': typeof EditProfileRoute
  '/login': typeof LoginRoute
  '/lost-and-found': typeof LostAndFoundRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-listings': typeof MyListingsRoute
  '/signup': typeof SignupRoute
  '/to-let': typeof ToLetRoute
  '/listing/$id': typeof ListingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/edit-profile'
    | '/login'
    | '/lost-and-found'
    | '/marketplace'
    | '/my-listings'
    | '/signup'
    | '/to-let'
    | '/listing/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/edit-profile'
    | '/login'
    | '/lost-and-found'
    | '/marketplace'
    | '/my-listings'
    | '/signup'
    | '/to-let'
    | '/listing/$id'
  id:
    | '__root__'
    | '/'
    | '/edit-profile'
    | '/login'
    | '/lost-and-found'
    | '/marketplace'
    | '/my-listings'
    | '/signup'
    | '/to-let'
    | '/listing/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditProfileRoute: typeof EditProfileRoute
  LoginRoute: typeof LoginRoute
  LostAndFoundRoute: typeof LostAndFoundRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MyListingsRoute: typeof MyListingsRoute
  SignupRoute: typeof SignupRoute
  ToLetRoute: typeof ToLetRoute
  ListingIdRoute: typeof ListingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-profile': {
      id: '/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof EditProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lost-and-found': {
      id: '/lost-and-found'
      path: '/lost-and-found'
      fullPath: '/lost-and-found'
      preLoaderRoute: typeof LostAndFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-listings': {
      id: '/my-listings'
      path: '/my-listings'
      fullPath: '/my-listings'
      preLoaderRoute: typeof MyListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/to-let': {
      id: '/to-let'
      path: '/to-let'
      fullPath: '/to-let'
      preLoaderRoute: typeof ToLetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditProfileRoute: EditProfileRoute,
  LoginRoute: LoginRoute,
  LostAndFoundRoute: LostAndFoundRoute,
  MarketplaceRoute: MarketplaceRoute,
  MyListingsRoute: MyListingsRoute,
  SignupRoute: SignupRoute,
  ToLetRoute: ToLetRoute,
  ListingIdRoute: ListingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
